### ISSUE TITLE
SQLException when using auto_increment in MySQL 5.7

### ISSUE THREAD

**Issue by kloudsamurai** [andrewoma/kwery#5]
This is my first object that utilizes auto increment in MySQL. I've set the DAO to utilize generated keys:

``` kotlin
/**
 * @author [David Maple](mailto:d@davemaple.com)
 */
data class Topic(
        val name: String,
        val dateCreated: LocalDateTime = LocalDateTime.now(),
        val dateModified: LocalDateTime = LocalDateTime.now(),
        val version: Long = 1,
        val id: Int = 0
)

/**
 * @author [David Maple](mailto:d@davemaple.com)
 */
object topicTable : Table<Topic, Int>("topic", TableConfiguration(
        standardDefaults + timeDefaults,
        standardConverters + timeConverters,
        camelToLowerUnderscore
)), VersionedWithLong {
    val Id by topicTable.col(Topic::id, id = true)
    val Name by topicTable.col(Topic::name)
    val DateCreated by topicTable.col(Topic::dateCreated)
    val DateModified by topicTable.col(Topic::dateModified)
    val Version by topicTable.col(Topic::version, version = true)

    override fun idColumns(id: Int) = setOf(Id of id)

    override fun create(value: Value<Topic>) = Topic(
            id = value of Id,
            dateCreated = value of DateCreated,
            dateModified = value of DateModified,
            name = value of Name,
            version = value of Version
    )
}

/**
 * @author [David Maple](mailto:d@davemaple.com)
 */
class TopicDao(session: Session) : AbstractDao<Topic, Int>(
        session,
        topicTable,
        { it.id },
        "bigint(20) unsigned",
        IdStrategy.Generated,
        0
) {
    init {
        addListener(object : Listener {
            override fun onEvent(session: Session, event: Event) {
                if (event is TransformingEvent && event.new is Topic) {
                    val entity = event.new as Topic
                    if (event is PreInsertEvent) {
                        event.transformed = entity.copy(
                                dateCreated = LocalDateTime.now(),
                                dateModified = LocalDateTime.now()
                        )
                    }
                    if (event is PreUpdateEvent && event.new is Topic) {
                        event.transformed = entity.copy(dateModified = LocalDateTime.now())
                    }
                }
            }
        })
    }
}
```

SQL looks like this:

``` sql
CREATE TABLE `topic` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) DEFAULT NULL,
  `date_created` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `date_modified` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
```

As you can see I do have an `id` column, yet when performing an INSERT via the DAO I get an unexpected SQLException. Logging shows an expected INSERT syntax:

``` sql
insert into topic(date_created, date_modified, name, version) 
values ('2016-05-22 11:07:59.876', '2016-05-22 11:07:59.876', 'Love/Romance', 1);
```

The stacktrace shows the following:

```
Failed to execute TopicDao.insert in 1.921 ms (761521.415 ms)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
Reason: Column 'id' not found.. TXN: 3

    at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1076)
    at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2580)
    at com.github.andrewoma.kwery.core.Row.int(Row.kt:47)
    at com.github.andrewoma.kwery.mapper.intConverter$1.invoke(Converters.kt:80)
    at com.github.andrewoma.kwery.mapper.intConverter$1.invoke(Converters.kt:80)
    at com.github.andrewoma.kwery.mapper.Table$rowMapper$1$1.of(Table.kt:300)
    at com.quote.topic.topicTable.create(TopicDao.kt:25)
```

Any idea what I need to change configuration wise to prevent this?

**Comment by andrewoma** [comment]
Does the insert statement work outside of kwery? I.e. using the mysql console?

**Comment by kloudsamurai** [comment]
It does:

```
14:33:22    insert into topic(date_created, date_modified, name, version)  values ('2016-05-22 11:07:59.876', '2016-05-22 11:07:59.876', 'Love/Romance', 1) 1 row(s) affected   0.006 sec
```

**Comment by andrewoma** [comment]
Strange. What about via jdbc. e.g. intellij's database console? I can't see anything wrong with what you're doing. I'll try to reproduce it locally

**Comment by kloudsamurai** [comment]
Works fine there as well.

![screen shot 2016-05-22 at 3 08 12 pm](https://cloud.githubusercontent.com/assets/3209030/15455922/8508ac98-202f-11e6-8095-4871c7a58700.png)

It also works fine if i remove the id = true property from Id -- but naturally then I don't see the auto generated ID reflected in the return of insert().

**Comment by andrewoma** [comment]
I can reproduce it. I should have looked at the stack trace more carefully.

The error is actually referring fetching the generated key after insert. JDBC has a few variations in this area (e.g. in Oracle you have to name the columns in the JDBC statement). 

I haven't tried mysql with autoincrement via kwery (I use it with postgres), so will have to do a bit of experimentation.

**Comment by andrewoma** [comment]
OK, the issue is that mysql requires you to fetch the generated key using `rs.get(1)` not `rs.get("id")`.

I'll have to make a change to AbstractDao to allow for this - I have a hack that works, but need to think about the cleanest way to approach it.

**Comment by andrewoma** [comment]
Hi Dave, I pushed a quick fix to master here: https://github.com/andrewoma/kwery/commit/40e9a567e147e8fd33764019c997d46ff42dc763

I'll add some MySQL tests for the mapper module I guess to try and catch such issues

**Comment by andrewoma** [comment]
FYI, I've pushed out release 0.11 that includes this fix
